### ISSUE TITLE
Trying to create and start private network throws errors

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algorand-builder#221]
This happens usually when I try to create a network:
```
$ make create-private-net
https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782 100000
Error creating private network: invalid API token
make: *** [Makefile:6: create-private-net] Error 1
```
When the creation manage to works I also usually get:

```
$ make start-private-net
goal network start -r ./node_data
Error starting deployed network: node exited with an error code, check node.log for more details : exit status 1
make: *** [Makefile:15: start-private-net] Error 1
```

I didn't manage to find the node.log.

Also after the 2 commands were working I had some trouble with setup-master-account:

```
$ make setup-master-account
ERRO[0000] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0000c81c0, 0xc0000104a8, 0xc0003b5730)
        runtime/debug/stack.go:24 +0x9f
github.com/algorand/go-algorand/logging.logger.Errorf(0xc0000c81c0, 0xc0000104a8, 0x11956d0, 0x42, 0xc0003ed890, 0x3, 0x3)
        github.com/algorand/go-algorand/logging/log.go:229 +0x4a
github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD(0xc0002ad2b0, 0x3c, 0x0, 0xc0004e6960, 0xc0004adb70)
        github.com/algorand/go-algorand/nodecontrol/kmdControl.go:204 +0xc96
github.com/algorand/go-algorand/libgoal.(*Client).getKMDClient(0xc0002ad250, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:240 +0x77
github.com/algorand/go-algorand/libgoal.(*Client).ensureKmdClient(...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:185
github.com/algorand/go-algorand/libgoal.(*Client).init(0xc0002ad250, 0x7fffe1d03ccc, 0x48, 0xc0004e6660, 0x51, 0xc0004e6780, 0x53, 0xc0000360b0, 0x8, 0x1, ...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:163 +0x286
github.com/algorand/go-algorand/libgoal.MakeClientFromConfig(0x7fffe1d03ccc, 0x48, 0xc0004e6660, 0x51, 0xc0004e6780, 0x53, 0xc0000360b0, 0x8, 0x1, 0xc0004adb50, ...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:128 +0x9f
main.ensureGoalClient(0x7fffe1d03ccc, 0x48, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:380 +0x16e
main.ensureKmdClient(...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:363
main.getWalletHandleMaybePassword(0x7fffe1d03ccc, 0x48, 0x0, 0x0, 0xc000264600, 0xc0002ad900, 0xea8d21, 0xc0004c0000, 0x14a, 0x34a, ...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:407 +0xe9
main.ensureWalletHandleMaybePassword(0x7fffe1d03ccc, 0x48, 0x0, 0x0, 0xc000118400, 0x0, 0x1, 0x1712280, 0xc0003bd6ea, 0xc0002ada1f, ...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:394 +0x75
main.ensureWalletHandle(...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:389
main.glob..func9(0x20707c0, 0xc0003e8280, 0x0, 0x2)
        github.com/algorand/go-algorand/cmd/goal/account.go:460 +0xfa
github.com/spf13/cobra.(*Command).execute(0x20707c0, 0xc0003e8220, 0x2, 0x2, 0x20707c0, 0xc0003e8220)
        github.com/spf13/cobra@v0.0.3/command.go:766 +0x29f
github.com/spf13/cobra.(*Command).ExecuteC(0x2066180, 0x0, 0x119df1f, 0xc3)
        github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        github.com/algorand/go-algorand/cmd/goal/commands.go:155 +0x98  file=kmdControl.go function="github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD" line=204
ERRO[0000] /mnt/c/Users/LucaM/algolend/backend/infrastructure/node_data/PrimaryNode/kmd-v0.5: kmd data dir exists but is too permissive (777), change to (700)  file=kmdControl.go function="github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD" line=204
Cannot contact Algorand node: kmd data dir not secure
goal account import -m "enforce drive foster uniform cradle tired win arrow wasp melt cattle chronic sport dinosaur announce shell correct shed amused dismiss mother jazz task above hospital" -d `pwd`/node_data/PrimaryNode
ERRO[0000] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0002e4690, 0xc00028a0a0, 0xc0003d11f0)
        runtime/debug/stack.go:24 +0x9f
github.com/algorand/go-algorand/logging.logger.Errorf(0xc0002e4690, 0xc00028a0a0, 0x11956d0, 0x42, 0xc0004d2300, 0x3, 0x3)
        github.com/algorand/go-algorand/logging/log.go:229 +0x4a
github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD(0xc00039f760, 0x3c, 0x0, 0xc0002c3f80, 0xc000483ed0)
        github.com/algorand/go-algorand/nodecontrol/kmdControl.go:204 +0xc96
github.com/algorand/go-algorand/libgoal.(*Client).getKMDClient(0xc00039f700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:240 +0x77
github.com/algorand/go-algorand/libgoal.(*Client).ensureKmdClient(...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:185
github.com/algorand/go-algorand/libgoal.(*Client).init(0xc00039f700, 0x7ffff8c17498, 0x48, 0xc0002c3c80, 0x51, 0xc0002c3da0, 0x53, 0xc000132010, 0x8, 0x1, ...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:163 +0x286
github.com/algorand/go-algorand/libgoal.MakeClientFromConfig(0x7ffff8c17498, 0x48, 0xc0002c3c80, 0x51, 0xc0002c3da0, 0x53, 0xc000132010, 0x8, 0x1, 0xc000483eb0, ...)
        github.com/algorand/go-algorand/libgoal/libgoal.go:128 +0x9f
main.ensureGoalClient(0x7ffff8c17498, 0x48, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:380 +0x16e
main.ensureKmdClient(...)
        github.com/algorand/go-algorand/cmd/goal/commands.go:363
main.glob..func20(0x206f260, 0xc0002833c0, 0x0, 0x4)
        github.com/algorand/go-algorand/cmd/goal/account.go:1088 +0x1af
github.com/spf13/cobra.(*Command).execute(0x206f260, 0xc000283340, 0x4, 0x4, 0x206f260, 0xc000283340)
        github.com/spf13/cobra@v0.0.3/command.go:766 +0x29f
github.com/spf13/cobra.(*Command).ExecuteC(0x2066180, 0x0, 0x119df1f, 0xc3)
        github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        github.com/algorand/go-algorand/cmd/goal/commands.go:155 +0x98  file=kmdControl.go function="github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD" line=204
ERRO[0000] /mnt/c/Users/LucaM/algolend/backend/infrastructure/node_data/PrimaryNode/kmd-v0.5: kmd data dir exists but is too permissive (777), change to (700)  file=kmdControl.go function="github.com/algorand/go-algorand/nodecontrol.(*KMDController).StartKMD" line=204
Cannot contact Algorand node: kmd data dir not secure
```

And another error about the wrong api key in after the same command(make setup-master-account) but I can't manage to simulate it again

**Comment by robert-zaremba** [comment]
I've added `./node_data` check - could you pull the latest master and recheck?
If it won't work, please provide more information about your setup:
* what's your algorand version (`algod -v`)?
* what's your OS?
* What shell are you using?

**Comment by Lumene98** [comment]
> 
> 
> I've added `./node_data` check - could you pull the latest master and recheck?
> If it won't work, please provide more information about your setup:
> 
>     * what's your algorand version (`algod -v`)?
> 
>     * what's your OS?
> 
>     * What shell are you using?

Now it is fixed, thanks!
