### ISSUE TITLE
yarn workspaces run test fails at @algorand-builder/algob

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algorand-builder#224]
Only one test fails:

```
1) argumentTypes
       Input file type
         Should throw if the file isn't readable:
     AssertionError: BuilderError number 302 expected, but no Error was thrown
      at Object.expectBuilderError (test/helpers/errors.ts:65:9)
      at Context.<anonymous> (test/internal/core/params/argument-types.ts:242:7)
```

**Comment by ratik21** [comment]
@Lumene98 could you please share your OS?

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 could you please share your OS?

Ubuntu 20.04 LTS

**Comment by ratik21** [comment]
@Lumene98 could you try running the tests now (after taking `git pull`) ?

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 could you try running the tests now (after taking `git pull`) ?

Same result after last change
